### PR TITLE
spyking circus extraction

### PR DESCRIPTION
**Pull request by gfetterman**

### CODE REVIEW

**Comment by kylerbrown** [comment]
Hey Graham this is really great. One issue: all the other bark converters use seconds as a time base for event data. This is less efficient for storage, but is just they way everything seems to do things (praat, plexon, wave_clus)

I'd like the units to be seconds, to keep things consistent. If you still want the option of samples output, I'm fine with that as a non-default option.

**Comment by kylerbrown** [comment]
I'd also prefer if the `template_name` column was `name` instead, in keeping with bark conventions.

**Comment by kylerbrown** [comment]
Finally, perhaps chop off the `temp_` part of the template name? eg `1` instead of `temp_1`? What do you think?

**Comment by gfetterman** [comment]
No problem to change the `start` units from samples to seconds. I left it in samples out of laziness.

Also no problem changing `template_name` to `name` if you prefer. I thought being more explicit might be good, but don't feel strongly.

I do think it might be worth it to keep the longer template names, though, to maintain compatibility with the SC data still in the SC files. Another option would be to preserve that information in the `meta` file. (Actually now that I say it I think I prefer this, and will do it this way.)

**Comment by kylerbrown** [comment]
Fantastic, thanks!

**Pull request merged**
